version: '3.9'
services:
  postgresql:
    container_name: postgres_container
    image: postgres
    restart: always
    volumes:
      - /home/julio/projects/postgres-container-docker/data:/var/lib/postgresql/data
      - ./init_db.sql:/docker-entrypoint-initdb.d/init_db.sql
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=${POSTGRES_DATABASE:-postgres_db}
      - POSTGRES_USER=${POSTGRES_USER:-root}
    networks:
      - app-network
networks:
  app-network:
    driver: bridge